USE [master]
GO

/****** Object:  Database [GraphsDatabase]    Script Date: 11/24/2016 6:42:16 PM ******/
CREATE DATABASE [GraphsDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GraphsDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GraphsDatabase.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GraphsDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GraphsDatabase_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GraphsDatabase] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GraphsDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GraphsDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GraphsDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GraphsDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GraphsDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GraphsDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [GraphsDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GraphsDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GraphsDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GraphsDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GraphsDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GraphsDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GraphsDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GraphsDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GraphsDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GraphsDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GraphsDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GraphsDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GraphsDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GraphsDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GraphsDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GraphsDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GraphsDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GraphsDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [GraphsDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [GraphsDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GraphsDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GraphsDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GraphsDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GraphsDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GraphsDatabase] SET  READ_WRITE 
GO

