//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.FrontEndServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FrontEndServiceReference.IFrontEndService")]
    public interface IFrontEndService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetNodes", ReplyAction="http://tempuri.org/IFrontEndService/GetNodesResponse")]
        Shared.Node[] GetNodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFrontEndService/GetNodes", ReplyAction="http://tempuri.org/IFrontEndService/GetNodesResponse")]
        System.Threading.Tasks.Task<Shared.Node[]> GetNodesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFrontEndServiceChannel : Client.FrontEndServiceReference.IFrontEndService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FrontEndServiceClient : System.ServiceModel.ClientBase<Client.FrontEndServiceReference.IFrontEndService>, Client.FrontEndServiceReference.IFrontEndService {
        
        public FrontEndServiceClient() {
        }
        
        public FrontEndServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FrontEndServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FrontEndServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FrontEndServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Shared.Node[] GetNodes() {
            return base.Channel.GetNodes();
        }
        
        public System.Threading.Tasks.Task<Shared.Node[]> GetNodesAsync() {
            return base.Channel.GetNodesAsync();
        }
    }
}
