//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DomainSpecificServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DomainSpecificServiceReference.IDomainSpecificService")]
    public interface IDomainSpecificService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDomainSpecificService/FindShortestPath", ReplyAction="http://tempuri.org/IDomainSpecificService/FindShortestPathResponse")]
        Shared.Node[] FindShortestPath(int firstNodeId, int secondNodeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDomainSpecificService/FindShortestPath", ReplyAction="http://tempuri.org/IDomainSpecificService/FindShortestPathResponse")]
        System.Threading.Tasks.Task<Shared.Node[]> FindShortestPathAsync(int firstNodeId, int secondNodeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDomainSpecificServiceChannel : Client.DomainSpecificServiceReference.IDomainSpecificService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DomainSpecificServiceClient : System.ServiceModel.ClientBase<Client.DomainSpecificServiceReference.IDomainSpecificService>, Client.DomainSpecificServiceReference.IDomainSpecificService {
        
        public DomainSpecificServiceClient() {
        }
        
        public DomainSpecificServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DomainSpecificServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomainSpecificServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomainSpecificServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Shared.Node[] FindShortestPath(int firstNodeId, int secondNodeId) {
            return base.Channel.FindShortestPath(firstNodeId, secondNodeId);
        }
        
        public System.Threading.Tasks.Task<Shared.Node[]> FindShortestPathAsync(int firstNodeId, int secondNodeId) {
            return base.Channel.FindShortestPathAsync(firstNodeId, secondNodeId);
        }
    }
}
